//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Silvelight2Angular.Framework.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Silverlight2AngularModelContainer : DbContext
    {
        public Silverlight2AngularModelContainer()
            : base("name=Silverlight2AngularModelContainer")
        {
            BaseEntities = Set<BaseEntity>();
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Page> Pages { get; set; }
        internal virtual DbSet<BaseEntity> BaseEntities { get; set; }
    }
}
